version: "3.8"

services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 9229:9229
    networks:
      - demo-account-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  demo-account-app:

volumes:
  data-store:
